CREATE DATABASE {{MYSQL_DATABASE}} CHARACTER SET utf8;
CREATE USER '{{MYSQL_USER}}'@'%' IDENTIFIED BY '{{MYSQL_PASSWORD}}';
GRANT ALL PRIVILEGES ON {{MYSQL_DATABASE}}.* TO '{{MYSQL_USER}}'@'%' IDENTIFIED BY '{{MYSQL_PASSWORD}}';
FLUSH PRIVILEGES;